# Generated by Django 5.2.10 on 2026-02-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='niveau_scolaire',
            field=models.CharField(blank=True, choices=[('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6e', '6ème'), ('5e', '5ème'), ('4e', '4ème'), ('3e', '3ème'), ('2nde', 'Seconde'), ('1ere', 'Première'), ('Tle', 'Terminale')], help_text="Niveau scolaire de l'élève.", max_length=10, null=True),
        ),
    ]
