# Generated by Django 5.2.10 on 2026-02-11 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_utilisateur_niveau_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='tuteur',
            field=models.ForeignKey(blank=True, help_text='Tuteur assigné à cet élève (optionnel).', limit_choices_to={'role': 'tuteur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to=settings.AUTH_USER_MODEL),
        ),
    ]
